import type { Metadata } from 'next'
import { Inter as FontSans } from "next/font/google"
import './globals.css'

import { ThemeProvider } from "@/components/theme/theme-provider"
import { cn } from '@/lib/utils'

export const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  /* Recomendado pelo chadcn adicioar <html lang="en" suppressHydrationWarning> */
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  )
}
